version: '3'
services:
  crypto-lottery:
    # network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-lottery
    container_name: crypto-lottery-app
    restart: always
    ports:
      - 1237:3000
    # environment:
    # env_file:
    #   - ./.env.production.local
